### ISSUE TITLE
Heroku mudou as regras

### ISSUE THREAD

**Issue by fernandodrcampos** [lucas231090/Agro-4.0-UFPR-Doutorado-Lucas#1]
Olá, o Heroku alterou suas regras de deploy e retirou do ar o plano gratuito. 
Dica: procure outra plataforma para deixar a demonstração.

back-end funcionando muito bem. Estou aprendendo bastante com o app

**Comment by lucas231090** [comment]
feito.
Novo dominio para a API.
https://api-agro-render.onrender.com/
